## Assuming the .travis.yml file is in the project directory, and there is a separate sub-directory for each service
## Use either `docker-compose` or individual `docker build` commands

language: node_js
node_js:
  - 18

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

## Build
script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-feed ./project/udagram-api-feed
  - docker build -t udagram-api-user ./project/udagram-api-user
  - docker build -t udagram-frontend ./project/udagram-frontend
  - docker build -t udagram-reverseproxy ./project/udagram-reverseproxy
## Tagging
  - docker tag udagram-api-feed michfelip/udagram-api-feed:v1
  - docker tag udagram-api-user michfelip/udagram-api-user:v1
  - docker tag udagram-frontend michfelip/udagram-frontend:v1
  - docker tag udagram-reverseproxy michfelip/udagram-reverseproxy:v1
```bash

## Push
## Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push michfelip/udagram-api-feed:v1
  - docker push michfelip/udagram-api-user:v1
  - docker push michfelip/udagram-frontend:v1
  - docker push michfelip/udagram-reverseproxy:v1