apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    service: frontend
spec:
  replicas: 2
  selector: 
    matchLabels: 
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: michfelip/udagram-frontend
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
          - name: URL
            valueFrom:
              configMapKeyRef:
                name: env-configmap
                key: URL
          - name: AWS_BUCKET
            valueFrom:
              configMapKeyRef:
                name: env-configmap
                key: AWS_BUCKET
          - name: AWS_PROFILE
            valueFrom:
              configMapKeyRef:
                name: env-configmap
                key: AWS_PROFILE
          - name: AWS_REGION
            valueFrom:
              configMapKeyRef:
                name: env-configmap
                key: AWS_REGION
          - name: JWT_SECRET
            valueFrom:
              configMapKeyRef:
                name: env-configmap
                key: JWT_SECRET
          - name: POSTGRESS_DB
            valueFrom:
              configMapKeyRef:
                name: env-configmap
                key: POSTGRESS_DB
          - name: POSTGRESS_HOST
            valueFrom:
              configMapKeyRef:
                name: env-configmap
                key: POSTGRESS_HOST
          - name: POSTGRESS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: env-secret
                key: POSTGRESS_PASSWORD
          - name: POSTGRESS_USERNAME
            valueFrom:
              secretKeyRef:
                name: env-secret
                key: POSTGRESS_USERNAME      
        volumeMounts:
          - name: aws-secret
            mountPath: "/root/.aws/"
            readOnly: true        
      restartPolicy: Always
      volumes:
      - name: aws-secret
        secret:
          secretName: aws-secret
